const position = { x: 0, y: 0 };
const edgeType = "step";

export const initialNodes = [
  {
    id: "1a",
    type: "personNode",
    data: { name: "input" },
    position,
  },
  {
    id: "1b",
    type: "personNode",
    data: { name: "placeholderChild" },
    position,
    hidden: true,
  },
  {
    id: "2",
    type: "personNode",
    data: { name: "node 2" },
    position,
  },
  {
    id: "2a",
    type: "personNode",
    data: { name: "node 2a" },
    position,
  },
  {
    id: "2b",
    type: "personNode",
    data: { name: "node 2b" },
    position,
  },
  {
    id: "2c",
    type: "personNode",
    data: { name: "node 2c" },
    position,
  },
  {
    id: "2d",
    type: "personNode",
    data: { name: "node 2d" },
    position,
  },
  {
    id: "3a",
    type: "personNode",
    data: { name: "node 3a" },
    position,
  },
  {
    id: "3b",
    type: "personNode",
    data: { name: "node 3b" },
    position,
  },
  {
    id: "4",
    type: "personNode",
    data: { name: "node 4" },
    position,
  },
  {
    id: "5",
    type: "personNode",
    data: { name: "node 5" },
    position,
  },
  {
    id: "6",
    type: "personNode",
    data: { name: "output" },
    position,
  },
  { id: "7", type: "personNode", data: { name: "output" }, position },
];

export const initialEdges = [
  {
    id: "e1a2",
    source: "1a",
    target: "2",
    sourceHandle: "parent",
    targetHandle: "child",
    type: edgeType,
  },
  {
    id: "e1a3a",
    source: "1a",
    target: "3a",
    sourceHandle: "parent",
    targetHandle: "child",
    type: edgeType,
  },
  {
    id: "e3b1b",
    source: "3b",
    target: "1b",
    sourceHandle: "parent",
    targetHandle: "child",
    type: edgeType,
  },
  {
    id: "e3a1b",
    source: "3a",
    target: "1b",
    sourceHandle: "parent",
    targetHandle: "child",
    type: edgeType,
  },
  {
    id: "e22a",
    source: "2",
    target: "2a",
    sourceHandle: "parent",
    targetHandle: "child",
    type: edgeType,
  },
  {
    id: "e22b",
    source: "2",
    target: "2b",
    sourceHandle: "parent",
    targetHandle: "child",
    type: edgeType,
  },
  {
    id: "e22c",
    source: "2",
    target: "2c",
    sourceHandle: "parent",
    targetHandle: "child",
    type: edgeType,
  },
  {
    id: "e2c2d",
    source: "2c",
    target: "2d",
    sourceHandle: "parent",
    targetHandle: "child",
    type: edgeType,
  },
  {
    id: "e2a5",
    source: "2a",
    target: "5",
    sourceHandle: "parent",
    targetHandle: "child",
    type: edgeType,
  },
  {
    id: "e45",
    source: "4",
    target: "5",
    sourceHandle: "parent",
    targetHandle: "child",
    type: edgeType,
  },
  {
    id: "e56",
    source: "5",
    target: "6",
    sourceHandle: "parent",
    targetHandle: "child",
    type: edgeType,
  },
  {
    id: "e57",
    source: "5",
    target: "7",
    sourceHandle: "parent",
    targetHandle: "child",
    type: edgeType,
  },
];
